name: pyvwf
channels:
- conda-forge
- bioconda
dependencies:
- python>=3.10
- pandas=2.2.2
- dask=2025.11.0
- xarray=2024.9.0
- utm=0.7.0
- scipy=1.14.1
- scikit-learn=1.5.2
- matplotlib=3.9.2
- seaborn=0.13.2
- openpyxl=3.1.5
- netcdf4=1.7.1
- bottleneck=1.4.0