[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyvwf"
version = "0.1.0"
description = "Python Virtual Wind Farm (PyVWF) model"
readme = "README.md"
requires-python = ">=3.10"

[tool.setuptools]
packages = ["vwf"]
